# Generated by Django 4.0.3 on 2022-04-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='postado',
            field=models.BooleanField(default=False),
        ),
    ]
